export const confirmButtonText = 'Confirm'
export const SaveButtonText = 'Save'
export const cancelButtonText = 'Cancel'
export const verifyButtonText = 'Verify'
export const loadingTitle = 'Loading...'

export const loginTitle = 'Login'
export const ForgotTitle = 'Forgot Password'
export const ChangePassTitle = 'Change Password'
export const ForgotLink = 'Forgot Password?'
export const ForgotRequest = 'Enter the email you used to register your account'
export const OtpTitle = 'OTP'
export const OtpRequest = 'You will get OTP via Email'
export const OtpReSendTitle = 'OTP code expires after '
export const LogoutTitle = 'Logout'

export const NavDashboard = 'Dashboard'
export const NavAccManager = 'Account Management'
export const NavAccEmployee = 'Employees Account'
export const NavRoles = 'Roles'
export const NavPermissions = 'Permissions'

export const CreateBtn = 'Create'
export const CreateAccInput = 'Enter email to create an account'
export const CreateInput = 'Enter name to create'
export const EditBtn = 'Edit'
export const DeleteBtn = 'Delete'
export const ViewProfileBtn = 'Profile'
export const SearchInput = 'Search'
